### ISSUE TITLE
 Is  RepBlock  the same as CPCA_BLOCK?

### ISSUE THREAD

**Issue by FRC1221** [Cuthbert-Huang/CPCANet#5]
Of course. I'm sorry to be a bother to you. It's called RepBlock class in [CPCANet.py](https://github.com/Cuthbert-Huang/CPCANet/blob/main/CPCANet/nnunet/network_architecture/CPCANet.py) (line 87).

_Originally posted by @Cuthbert-Huang in https://github.com/Cuthbert-Huang/CPCANet/issues/4#issuecomment-1636720383_

**Comment by Cuthbert-Huang** [comment]
Yes, the RepBlock class in our code is same as CPCA_Block in our paper.
